services:
  walkys-app:
    container_name: walkys-app
    hostname: walkys-app
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - walkys

  walkys-api:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: walkys-api
    hostname: walkys-api
    restart: unless-stopped
    volumes:
      - ./api:/api
      - ./api/data:/pb_data
    networks:
      - walkys
    ports:
      - "8090:8090"

networks:
  walkys:
    external: true
